<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title><g:if test="${session.pgTitle}">${session.pgTitle}</g:if><g:else>e-Governance</g:else></title>
		<link rel="icon" type="image/png" href="${resource(dir:'egov_img',file:'nationEmblem.png')}" style="max-width:50%; max-height:50%;">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        
        <link href="${resource(dir:'css/egov_css/',file:'bootstrap.min.css')}" rel="stylesheet" type="text/css" />
        <link href="${resource(dir:'css/egov_css/',file:'font-awesome.min.css')}" rel="stylesheet" type="text/css" />
        
        <!-- Theme style -->
        <link href="${resource(dir:'css/egov_css/',file:'AdminLTE.css')}" rel="stylesheet" type="text/css" />

    </head>
    <body>
        <!-- Automatic element centering using js -->
        <div class="center">
            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
			
            <!-- START LOCK SCREEN ITEM -->
            <div class="lockscreen-item">
                <div style="position:absolute; margin:0 auto; top:-65px; width:80%;">
                	<g:link controller="home" action="index">
                	<img src="${resource(dir:'egov_img',file:'logo.png')}" alt="Logo" width="100%" border="0">
                	</g:link>
                </div>
                <div style="display:block; clear:both;"></div>
                
                <div class="header"><h2>Log In</h2></div>
                <!-- User name -->
                
               	<g:if test='${flash.message}'>
					<div class='login_message'>
						${flash.message}
					</div>
				</g:if>
              <form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='on'>
				<table width="100%" border="0" cellspacing="0">
					<tr>
						<td width="100%" class="leftMe lableTxt"><g:message code="springSecurity.login.username.label" /></td>
					</tr>
					<tr>
						<td width="100%" class="centerMe"><input type='text' name='j_username' id='username' tabindex="1" class="form-control" placeholder="Username"/></td>
					</tr>
					<tr>
						<td width="100%" class="leftMe lableTxt"><g:message	code="springSecurity.login.password.label" /></td>
					</tr>
					<tr>
						<td width="100%" class="centerMe"><input type='password' name='j_password' id='password' tabindex="2" class="form-control" placeholder="Password"/></td>
					</tr>
					<tr>
						<td><input type="checkbox" name="remember_me"/> Remember me </td>
					</tr>
				</table>
				 <div class="footer">
                       <input type='submit' id="submit" class="btn bg-olive btn-block" value='${message(code: "springSecurity.login.button")}' />
   
                       <p><a href="#" style="float:left;">I forgot my password</a>
   
                       <a href="register-screen.html" style="float:right;" class="text-center">Sign Up</a></p>
                   </div>
				
			</form>
           </div>
            
            <div style="position:absolute; left:13%; bottom:-55px; width:50%;"><img src="${resource(dir:'egov_img',file:'avvp.png')}" alt="Amrita University Logo" border="0"></div>
            <div style="position:absolute; right:13%; bottom:-60px; width:15%;"><img src="${resource(dir:'egov_img',file:'cdac-logo.png')}" alt="CDAC Logo" width="90%" border="0"></div>
            <div style="display:block; clear:both;"></div>
        </div><!-- /.center -->

        <script src="${createLinkTo(dir:'js/egov_js/jquery_2.1.3',file:'jquery.min.js')}" type="text/javascript"></script>
        <script src="${createLinkTo(dir:'js/egov_js/bootstrap',file:'bootstrap.min.js')}" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>
